[tool.black]
line-length = 88
preview = true
exclude = '^/espresso'

[tool.isort]
profile = 'black'
multi_line_output = 3
skip_glob = ["espresso/*"]

[tool.coverage.run]
parallel = true
concurrency = ["multiprocessing"]
disable_warnings = ["no-data-collected"]
