name: Check coding style

on:
  push: [ "master" ]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Black Check
        uses: psf/black@stable

  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install isort
        run: |
          pip install isort
      - name: run isort
        run: |
          isort --check-only --quiet .
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install flake8
        run: |
          pip install flake8
      - name: run flake8
        run: |
          flake8 . --count --show-source --statistics
